---
# https://docs.docker.com/install/linux/docker-ce/debian/

- name: Ensure old versions of Docker are not installed.
  apt:
    name: "{{ packages }}"
    state: absent
    autoremove: yes
    purge: yes
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io

# Fix for Debian Buster: 'ImportError: No module named ssl_match_hostname'
# need to install python-backports.ssl-match-hostname prior to Pip installation!
# https://github.com/docker/docker-py/issues/1502#issuecomment-509898861
- name: Ensure that python-backports.ssl module is installed.
  apt:
    name: python-backports.ssl-match-hostname
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Install pre-requisite packages for Docker and docker-compose
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg2
    - software-properties-common
    - python3-setuptools
    - python3-pip

- name: Add Docker apt Debian key.
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 0EBFCD88
    state: present

- name: Add Docker Debian repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker.
  apt:
    name: docker-ce
    state: present
